version: "3.2"
services:
  pygdal:
    build: .
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - QUEUE=dsg-test-queue
      - IN_BUCKET=deafrica-staging-west
      - IN_PATH=L5-Ghana_original
      - OUT_BUCKET=test-results-deafrica-staging-west
      - OUT_PATH=L5-Ghana_original
      - CLEANUP=True
      - OVERWRITE=False
      - UPLOAD=False
      - IN_BUCKET=frontiersi-odc-data
      - LIMIT=1
    volumes:
      - .:/opt
