version: "3.2"
services:
  pygdal:
    build: .
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - QUEUE=dsg-test-queue
      - IN_BUCKET=deafrica-staging-west
      - IN_PATH=test
      - OUT_BUCKET=test-results-deafrica-staging-west
      - OUT_PATH=L5-Ghana_original_k8s
      - CLEANUP=True
      - OVERWRITE=False
      - UPLOAD=True
      - LIMIT=5
    volumes:
      - .:/opt
