version: "3.2"
services:
  pygdal:
    build: .
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - QUEUE=dsg-test-queue
      - IN_BUCKET=deafrica-staging-west
      - IN_PATH=test
      - OUT_BUCKET=deafrica-data
      - OUT_PATH=test
      - CLEANUP=True
      - OVERWRITE=False
      - UPLOAD=True
      - LIMIT=25
    volumes:
      - .:/opt
