version: "3.2"
services:
  pygdal:
    build: .
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=EXAMPLE
      - AWS_SECRET_ACCESS_KEY=OTHEREXAMPLE
      - AWS_SESSION_TOKEN=YOUMIGHTNOTWANTTHIS
      - CLEANUP=True
      - OVERWRITE=False
      - UPLOAD=False
      - IN_BUCKET=frontiersi-odc-data
    volumes:
      - .:/opt
