version: "3.2"
services:
  pygdal:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
      - CLEANUP=True
      - OVERWRITE=False
    # volumes:
    #   - .:/opt
