version: "3.2"
services:
  pygdal:
    build: .
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - QUEUE=alex-alive-queue
      - IN_BUCKET=deafrica-staging-west
      - IN_PATH=ama20200207
      - OUT_BUCKET=deafrica-data-dev
      - OUT_PATH=ama_test_2020
      - CLEANUP=True
      - OVERWRITE=False
      - UPLOAD=True
      - LIMIT=10
    volumes:
      - .:/opt
      - ~/.aws/credentials:/root/.aws/credentials
