apiVersion: v1
kind: Pod
metadata:
  name: test-l2c-pod
  labels:
    app: odc
  annotations:
    #iam.amazonaws.com/role: arn:aws:iam::565417506782:role/deafrica-ec2-s3_access
    iam.amazonaws.com/role: deafrica-ec2-s3_access
spec:
  containers:
  - name: datacube-core-container
    image: opendatacube/datacube-core
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: deafrica-eks
          key: postgres-username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deafrica-eks
          key: postgres-password
    - name: DB_USERNAME_DEAFRICA
      valueFrom:
        secretKeyRef:
          name: deafrica-datacube
          key: postgres-username
    - name: DB_PASSWORD_DEAFRICA
      valueFrom:
        secretKeyRef:
          name: deafrica-datacube
          key: postgres-password
    - name: DATACUBE_CONFIG_PATH
      value: "/opt/custom-config.conf" 
    - name: DB_DATABASE
      value: "deafrica"
    - name: DB_HOSTNAME
      value: "db-deafrica-eks-default.clgqttgwz3jw.us-west-2.rds.amazonaws.com"
    - name: DB_PORT
      value: "5432"
    - name: AWS_DEFAULT_REGION
      value: us-west-2
#    - name: AWS_ACCESS_KEY_ID
#      value: $()
#    - name: AWS_SECRET_ACCESS_KEY
#      value: 
      
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "docker-entrypoint.sh && while :; do echo '.'; sleep 5 ; done"]
  nodeSelector:
    beta.kubernetes.io/os: linux
