apiVersion: apps/v1
kind: Deployment
metadata:
  name: landsat-processor-deployment
  labels:
    app: python-landsat-processor
spec:
  replicas: 200
  selector:
    matchLabels:
      app: python-landsat-processor
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: deafrica-ec2-s3_access
      labels:
        app: python-landsat-processor
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - spot
      containers:
      - name: landsat-processor
        image: alexgleith/landsat-to-cog
        resources:
          requests:
            cpu: 1
            memory: 2048Mi
          limits:
            memory: 2048Mi
        env:
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: IN_BUCKET
          value: "deafrica-staging-west"
        - name: IN_PATH
          value: "ama20200207"
        - name: OUT_BUCKET
          value: "deafrica-data"
        - name: OUT_PATH
          value: "usgs/c1"
        - name: QUEUE
          value: "alex-alive-queue"
        - name: DLQUEUE
          value: "alex-dead-letter"
        - name: CLEANUP
          value: "True"
        - name: UPLOAD
          value: "True"
